[package]
name = "rustrush-pwhash"
version = "0.1.0"
authors = ["newpavlov <newpavlov@gmail.com>"]
edition = "2018"

[dependencies]
pbkdf2 = { version = "0.3", default-features = false }
sha2 = "0.8"
hmac = "0.7"
argon2rs = "0.2"
structopt = "0.2"
structopt-derive = "0.2"
base64 = "0.10"
